name: 'Validate Required Secrets'
description: 'Validates that required secrets are set before deployment'
inputs:
  s3-bucket-name:
    description: 'S3 bucket name secret'
    required: true
  s3-state-bucket-name:
    description: 'S3 state bucket name secret'
    required: true
  aws-role-arn:
    description: 'AWS role ARN secret'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Validate required secrets
      shell: bash
      run: |
        echo "🔍 Validating required configuration..."
        ERRORS=0
        
        if [ -z "${{ inputs.s3-bucket-name }}" ]; then
          echo "⚠️ WARNING: S3_BUCKET_NAME is not set, using fallback value"
          echo "   Consider setting S3_BUCKET_NAME in your GitHub repository variables for customization."
        else
          echo "✅ S3_BUCKET_NAME is set: ${{ inputs.s3-bucket-name }}"
        fi
        
        if [ -z "${{ inputs.s3-state-bucket-name }}" ]; then
          echo "⚠️ WARNING: S3_STATE_BUCKET_NAME is not set, using fallback value"
          echo "   Consider setting S3_STATE_BUCKET_NAME in your GitHub repository variables for customization."
        else
          echo "✅ S3_STATE_BUCKET_NAME is set: ${{ inputs.s3-state-bucket-name }}"
        fi
        
        if [ -z "${{ inputs.aws-role-arn }}" ]; then
          echo "❌ ERROR: AWS_ROLE_ARN secret is required but not set!"
          echo "   Please set AWS_ROLE_ARN in your GitHub repository secrets."
          ERRORS=$((ERRORS + 1))
        else
          echo "✅ AWS_ROLE_ARN is set"
        fi
        
        if [ $ERRORS -gt 0 ]; then
          echo ""
          echo "❌ $ERRORS required configuration(s) missing!"
          exit 1
        fi
        
        echo "✅ All required secrets validated successfully!"