name: 'Validate Required Secrets'
description: 'Validates that required secrets are set before deployment'
inputs:
  s3-bucket-name:
    description: 'S3 bucket name secret'
    required: true
  s3-state-bucket-name:
    description: 'S3 state bucket name secret'
    required: true
  aws-role-arn:
    description: 'AWS role ARN secret'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Validate required secrets
      shell: bash
      run: |
        if [ -z "${{ inputs.s3-bucket-name }}" ]; then
          echo "❌ ERROR: S3_BUCKET_NAME secret is required but not set!"
          echo "Please set S3_BUCKET_NAME in your GitHub repository or Production environment secrets."
          exit 1
        fi
        if [ -z "${{ inputs.s3-state-bucket-name }}" ]; then
          echo "❌ ERROR: S3_STATE_BUCKET_NAME secret is required but not set!"
          echo "Please set S3_STATE_BUCKET_NAME in your GitHub repository or Production environment secrets."
          exit 1
        fi
        if [ -z "${{ inputs.aws-role-arn }}" ]; then
          echo "❌ ERROR: AWS_ROLE_ARN secret is required but not set!"
          exit 1
        fi
        echo "✅ Required secrets validation passed"
    - name: Ensure Terraform state bucket exists
      shell: bash
      run: |
        STATE_BUCKET="${{ vars.S3_STATE_BUCKET_NAME }}"
        REGION="${{ needs.common-env.outputs.aws_region }}"
        
        if [ -z "$STATE_BUCKET" ]; then
          echo "❌ S3_STATE_BUCKET_NAME variable not set!"
          exit 1
        fi
        
        echo "Checking if state bucket $STATE_BUCKET exists..."
        if ! aws s3api head-bucket --bucket "$STATE_BUCKET" 2>/dev/null; then
          echo "Creating state bucket $STATE_BUCKET..."
          if [ "$REGION" = "us-east-1" ]; then
            aws s3api create-bucket --bucket "$STATE_BUCKET" --region "$REGION"
          else
            aws s3api create-bucket --bucket "$STATE_BUCKET" --region "$REGION" \
              --create-bucket-configuration LocationConstraint="$REGION"
          fi
          
          # Enable versioning on state bucket
          aws s3api put-bucket-versioning --bucket "$STATE_BUCKET" \
            --versioning-configuration Status=Enabled
          
          # Enable encryption
          aws s3api put-bucket-encryption --bucket "$STATE_BUCKET" \
            --server-side-encryption-configuration '{"Rules": [{"ApplyServerSideEncryptionByDefault": {"SSEAlgorithm": "AES256"}}]}'
          
          echo "✅ State bucket created successfully"
        else
          echo "✅ State bucket already exists"
        fi
