FROM nginx:alpine AS nginx-base

# Remove default nginx configuration
RUN rm /etc/nginx/conf.d/default.conf

# Copy custom nginx configuration files
COPY infra/nginx/nginx.conf /etc/nginx/nginx.conf
COPY infra/nginx/default.conf /etc/nginx/conf.d/default.conf

FROM node:20-alpine AS builder

WORKDIR /app

RUN npm install -g pnpm@latest

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

RUN npx nx run-many --target=build --all --exclude="*-e2e"

FROM nginx-base AS final

COPY --from=builder /app/apps/container/dist/ /usr/share/nginx/html/
COPY --from=builder /app/apps/headerMfe/dist/ /usr/share/nginx/html/headerMfe/
COPY --from=builder /app/apps/projectListMfe/dist/ /usr/share/nginx/html/projectListMfe/

# Expose port 80
EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"]
