# 1. Build stage
FROM node:20-alpine AS builder

WORKDIR /app

RUN npm install -g pnpm@latest

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

RUN npx nx run-many --target=build --all --exclude="*-e2e"

# 2. Production stage with Nginx
FROM nginx:alpine AS final

COPY infra/nginx/nginx.conf /etc/nginx/nginx.conf
COPY infra/nginx/default.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/apps/container/dist/ /usr/share/nginx/html/
COPY --from=builder /app/apps/headerMfe/dist/ /usr/share/nginx/html/headerMfe/
COPY --from=builder /app/apps/projectListMfe/dist/ /usr/share/nginx/html/projectListMfe/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
