version: '3.8'

services:
  thommf-portfolio-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "4200:80"
    container_name: thommf-portfolio-test
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=false"
      - "description=Production test environment for micro-frontend portfolio"
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge
    name: portfolio-test-network
