name: thommf-portfolio-e2e

services:
  frontend-static:
    build:
      context: ../../
      dockerfile: infra/e2e/Dockerfile.frontend-static
    ports:
      - "80:80"
    container_name: frontend-static
    restart: unless-stopped
    healthcheck:
      test: [
        "CMD-SHELL", 
        "curl --silent --fail http://localhost/ > /dev/null || exit 1"
      ]
      interval: 5s
      timeout: 3s
      retries: 6
      start_period: 5s
      start_interval: 2s
    volumes:
      - ../../:/workspace
      - ../../node_modules:/workspace/node_modules
    profiles:
      - app
      - e2e
    labels:
      - "traefik.enable=false"
      - "description=Production test environment for micro-frontend portfolio"
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d
      - CI=true
    networks:
      - e2e-network

  e2e-tests:
    container_name: e2e
    build:
      context: ../../
      dockerfile: infra/e2e/Dockerfile.e2e
    depends_on:
      frontend-static:
        condition: service_healthy
    volumes:
      - ../../:/workspace
      - ../../node_modules:/workspace/node_modules
    working_dir: /workspace
    profiles:
      - e2e
    environment:
      - CI=true
      - APP_URL=${APP_URL:-http://frontend-static}
      - DISPLAY=${DISPLAY}
      - NX_PROJECT=${NX_PROJECT}
    ipc: host
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    networks:
      - e2e-network

networks:
  e2e-network:
    driver: bridge
