name: CI

on:
  pull_request:
  workflow_call: # Allow this workflow to be called by other workflows

permissions:
  actions: read
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: Lint affected projects
        run: npx nx affected -t lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: Test affected projects
        run: npx nx affected -t test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: Build affected projects
        run: npx nx affected -t build

  discover-e2e:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: set-matrix
        name: Discover e2e projects
        shell: bash
        run: |
          set -euo pipefail
          dirs=$(ls -d apps/*-e2e 2>/dev/null || true)
          if [ -z "${dirs}" ]; then
            echo "matrix=[]" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          json="["
          for d in $dirs; do
            p=${d#apps/}
            json="$json{\"dir\":\"$d\",\"project\":\"$p\"},"
          done
          json="${json%,}]"
          echo "matrix=$json" >> "$GITHUB_OUTPUT"

  e2e:
    needs: discover-e2e
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        e2e: ${{ fromJSON(needs.discover-e2e.outputs.matrix) }}
    name: e2e-${{ matrix.e2e.project }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: Enable Docker BuildKit
        run: |
          echo '{"features":{"buildkit":true}}' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: E2E
        run: pnpm e2e:docker
        env:
          CI: true
          PLAYWRIGHT_BROWSERS_PATH: 0
          NX_PROJECT: ${{ matrix.e2e.project }}