name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy-infrastructure:
    uses: ./.github/workflows/deploy-infra.yml
    with:
      environment: 'Production'
      dry_run: false
    secrets: inherit